Added path to view individual review cards
DJHymers/fe-nc-games pull request #2
Opened 2023-04-18 13:33 UTC by DJHymers

2023-04-18 13:51 UTC, lewispricey requested changes
Great work on this ticket so far David!

Your codes super clean and easy to read which is awesome and its great to see the async/await in your api calls 👍 

Both the reviews and singleReview pages are not currently responsive and are currently exceeding the screen in mobile view.

Please could you tweak your CSS to make these responsive and submit another PR once you're ready (I'll send a screenshot over on Slack)

2023-04-18 13:51 UTC, lewispricey commented on src/components/SingleReview.jsx
> +  }, [review_id]);
Awesome to see the reviewId in your dependency array to ensure the useEffect triggers on manual url update!

2023-04-18 15:16 UTC, alexdevdavis requested changes
The responsive sizing is better for the single review page, but the reviews list doesn't change at all depending on screen size. 

- Consider working with `width` and/or `max-width` to prevent the site moving beyond the viewport

2023-04-19 11:15 UTC, lewispricey approved these changes
Great stuff David, thanks for implementing the feedback and making the page responsive.

Good to merge when you're ready 🚀

2023-04-19 11:17 UTC, merged